import localFont from "next/font/local";
import "./globals.css";
import ProtectedRouteAll from "@/components/ProtectedRouteAll/ProtectedRouteAll";
// import ProtectedRoute from "@/components/ProtectedRouteSalesperson/ProtectedRoute";
// import { useRouter } from "next/router";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <ProtectedRouteAll>
        {children}
      </ProtectedRouteAll>
      </body>
    </html>
  );
}



